name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment?'
        required: true
        default: 'staging'
      tag:
        description: 'user name'
        required: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "triggered manually by ${{ github.event.inputs.tag }}"



